# Generated by Django 5.2.5 on 2025-08-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradeDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticker', models.CharField(max_length=16)),
                ('action', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL'), ('HOLD', 'HOLD')], max_length=5)),
                ('prediction', models.IntegerField(blank=True, null=True)),
                ('qty', models.IntegerField(default=0)),
                ('price', models.FloatField(blank=True, null=True)),
                ('order_id', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'SUBMITTED'), ('FILLED', 'FILLED'), ('CLOSED', 'CLOSED'), ('IGNORED', 'IGNORED'), ('ERROR', 'ERROR')], default='SUBMITTED', max_length=16)),
                ('reason', models.TextField(blank=True, default='')),
                ('rsi_14', models.FloatField(blank=True, null=True)),
                ('macd_line', models.FloatField(blank=True, null=True)),
                ('macd_signal', models.FloatField(blank=True, null=True)),
                ('sma_50', models.FloatField(blank=True, null=True)),
                ('atr_14', models.FloatField(blank=True, null=True)),
                ('pnl_pct', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
