# Generated by Django 5.2.9 on 2025-12-12 16:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchwabToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(verbose_name='Encrypted Access Token')),
                ('refresh_token', models.TextField(verbose_name='Encrypted Refresh Token')),
                ('expires_in', models.IntegerField(verbose_name='Expires in seconds')),
                ('acquisition_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-acquisition_time'],
            },
        ),
    ]
